name: Push To GitHub Pages

on:
  push:
    branches:    
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install
      run: |
        yarn
      env:
        CI: true

    - name: Astro Build
      run: |
        yarn build
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: tillathe.blog